# Oracle profile
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration/oracle
